Module4 task1
htmlacademy-nodejs/835565-buy-and-sell-3 pull request #9
Opened 2021-06-04 22:00 UTC by bremxx

2021-06-05 13:05 UTC, Krabaton requested changes

2021-06-05 13:05 UTC, Krabaton commented on package.json
> +    "pug": "^3.0.2"
Мы устанавливаем только `npm i -E`

2021-06-05 13:05 UTC, Krabaton commented on src/mocks-generator/generate.js
> +    const offers = JSON.stringify(generateOffers(offersCount, titles, descriptions, categories, comments));
Мы уже отчетливо видим, что функция `generateOffers` начинает принимать все больше и больше параметров. Параметры `titles, descriptions, categories, comments` должны давно быть (когда их стало два) быть в одном параметре объекте `options`

2021-06-05 13:05 UTC, Krabaton commented on src/service/api/index.js
> +(async () => {
На самом деле это плохая конструкция. Она будет работать, но есть вероятность, что не успеет разрезолвится нормально. Такое лучше экспортировать как промис, а дальше уже ждать резолв, чтобы было наверняка. Но это видно из учебника раз у вас всех такое.

2021-06-05 13:05 UTC, Krabaton commented on src/service/api/index.js
> +(async () => {
В принципе начиная с версии 14.15 или даже раньше уже есть top level await и в этом вообще нет необходимости. Но боюсь устаревший linter не пропустит такое.

2021-06-05 13:05 UTC, Krabaton commented on src/service/middlewares/offer-validator.js
> +const defaultOfferKeys = [`title`, `picture`, `description`, `type`, `sum`, `categories`];
Вот такие вещи плохо, валидатор должен тащить ключи где они определены для моделей. А так ты два раза будешь код переписывать если поменяется, в модели и потом здесь.

2021-06-07 11:27 UTC, bremxx commented on package.json
> +    "pug": "^3.0.2"
Вообще не заметил, что он переустановил pug. При установке nanoid консоль выдала `found 1 high severity vulnerability`, ну я и пофиксил)) С чем связана эта уязвимость?

2021-06-07 11:32 UTC, bremxx commented on src/service/api/index.js
> +(async () => {
Да, такая реализация в учебнике.. честно был удивлен увидеть iife, напомнило как мы на втором уровне js делали экспорт через глобальный объект window и iife-хи)))

2021-06-07 12:14 UTC, Krabaton commented on package.json
> +    "pug": "^3.0.2"
Да ни с чем. Просто бывает, что даже patch обновление может нарушить работу программы. У меня на практике было всего раз.

2021-06-07 12:36 UTC, merged